version: "3.9"

services:
  web:
    build: .
    container_name: django_app_quiz_1
    command: python manage.py runserver 0.0.0.0:${DJANGO_PORT}
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    ports:
      - "8004:8000"
    env_file:
      - .env
    restart: always

volumes:
  static_volume:
