version: "3.9"

services:
  web:
    build: .
    container_name: django_app_quiz_1
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    ports:
      - "8004:8000"
    environment:
      - DEBUG=1
    restart: always

volumes:
  static_volume:
